name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  env:
    path: ../env
  logger: ^2.0.2+1

dev_dependencies:
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
