// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNnn__v7ImIm1GgR-leAhXvRokb_TcI08',
    appId: '1:977169289014:android:e22de9e19d55b347d52d97',
    messagingSenderId: '977169289014',
    projectId: 'fuji-film-recipe-dev',
    storageBucket: 'fuji-film-recipe-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYt8ZnO1fmtAueXGMNk9SlBl7dSpLEsQ0',
    appId: '1:977169289014:ios:082eecfc43be2bacd52d97',
    messagingSenderId: '977169289014',
    projectId: 'fuji-film-recipe-dev',
    storageBucket: 'fuji-film-recipe-dev.appspot.com',
    iosClientId: '977169289014-d8u9ikq5lt6ib6glvqepjisareouasmj.apps.googleusercontent.com',
    iosBundleId: 'com.babayo.fujiFilmRecipe.dev',
  );
}
